### ISSUE TITLE
Homing Z separately on CoreXY doesn't work

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#107]
Taken from http://forums.reprap.org/read.php?147,33082,437813#msg-437813 : 

*It homes all the axes simultaneously correctly with the "G28" command. It fails to home the Z Axis separately with the "G28 Z0" (I'm using pronterface).*

**Comment by youssefaly97** [comment]
Should be fixed though, at least for the sake of consistency.

**Comment by Traumflug** [comment]
Excellent! Picked to experimental and topic branch removed. :-)
