### ISSUE TITLE
What is copier.c/.h?

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#115]
@triffid, do you remember what the plan with copier.c/.h was? These two files are apparently used nowhere. First commit bringing these files in says

    First write-up of firmware copy routine- totally untested!

**Comment by triffid** [comment]
The idea was to be able to program another board from your electronics
without PC intervention, but reprap never seemed to go down that road

**Comment by Traumflug** [comment]
Thanks for the explanation, @triffid. I've removed them.
