### ISSUE TITLE
Simulator compile issues on Ubuntu 14.04

### ISSUE THREAD

**Issue by RaD** [Traumflug/Teacup_Firmware#125]
Hello, 
I have sucessfully built the firmware itself but still can not build simulator for it:

    rad@n150:~/reprap/PCB/Teacup_Firmware$ LANG=C make -f Makefile-SIM
      CC        build/sim/dda.o
    In file included from dda.c:14:0:
    dda_maths.h: In function 'um_to_steps':
    dda_maths.h:32:3: warning: implicit declaration of function 'pgm_read_dword' [-Wimplicit-function-declaration]
      CC        build/sim/dda_kinematics.o
    In file included from dda_kinematics.c:8:0:
    dda_maths.h: In function 'um_to_steps':
    dda_maths.h:32:3: warning: implicit declaration of function 'pgm_read_dword' [-Wimplicit-function-declaration]
      CC        build/sim/dda_maths.o
    In file included from dda_maths.c:6:0:
    dda_maths.h: In function 'um_to_steps':
    dda_maths.h:32:3: warning: implicit declaration of function 'pgm_read_dword' [-Wimplicit-function-declaration]
      CC        build/sim/delay_sim.o
    In file included from ./delay.h:4:0,
                     from simulator/delay_sim.c:3:
    /usr/lib/avr/include/stdint.h:142:17: error: conflicting types for 'intptr_t'
    /usr/include/unistd.h:268:20: note: previous declaration of 'intptr_t' was here
    make: *** [build/sim/delay_sim.o] Error 1

What's wrong there?

**Comment by Traumflug** [comment]
> dda_maths.h:32:3: warning: implicit declaration of function 'pgm_read_dword' [-Wimplicit-function-declaration]

pgm_read_dword() reads from flash, which isn't available on a PC. It shoud read from RAM (normal memory) instead. Something like a

    #define pgm_read_dword(x) *(x)

should solve this. Now, the simulator worked before, so there's likely already a solution for this. Just can't find it right now. @phord, do you have an idea?

> /usr/lib/avr/include/stdint.h:142:17: error: conflicting types for 'intptr_t'
> /usr/include/unistd.h:268:20: note: previous declaration of 'intptr_t' was here

It's unclear to me why the AVR version gets included at all. Shouldn't happen.

**Comment by phord** [comment]
Fixed in a80433d4188559b7fe517de37ae37a0f445b2e3a

**Comment by Traumflug** [comment]
Thanks. Picked to this repo.

**Comment by Traumflug** [comment]
Uhm. I've seen the issue-125 branch appeared again. The one commit on this branch is on experimental already. OK to delete this branch?

**Comment by phord** [comment]
Yep. Not sure why it showed up again.
