### ISSUE TITLE
Configtool: firmware baud rate != bootloader baud rate

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#133]
Firmware baud rate is misused as avrdude baud rate. These can differ, e.g. bootloaders typically use 115200 baud, while 230400 or 250000 baud are quite prpular for the firmware. For the cases where it differs, it's a showstopper, uploading impossible. There are already a few TODOs in configtool.py and configtool/*.py which hint on where to fix this.

**Comment by jbernardis** [comment]
This issue is addressed in branch configtoolPhaseA
