### ISSUE TITLE
Configtool: editing a non-thermistor fails

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#135]
Editing a non-thermistor fails, because these dummy-characters don't validate (background pink), despite they're not needed.

I admit, this is something I (@Traumflug) introduced myself. Creating such sensors (e.g. PT100 or AD595) works, but saving, re-loading and trying to edit them fails. It's a (to me welcome) artefact of the code to show "N", "O", "N" and "E" in these unused fields (gives a hint to the user), but unused fields should always validate.

**Comment by jbernardis** [comment]
This issue is addressed by branch configtoolPhaseB
