### ISSUE TITLE
Configtool: drop "successful" dialogs

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#136]
All these "saved successfully" and "successfully saved" should IMHO be removed. When saving something, this outcome is expected, because it only happens on a menu selection (check this!) or after a confirmation dialog (check this as well!). Confirming expected outcomes is, well, clutter. iPhone apps wouldn't do this.

There's even another visual feedback between saved and unsaved: this asterisk in the board/printer tab, which appears only for unsaved boards/printers and vanishes on saving. Much better, IMHO.

**Comment by jbernardis** [comment]
This issue is addressed in branch configtoolPhaseA
