### ISSUE TITLE
DEBUG should be removed from Configtool and config/printer*

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#137]
DEBUG should be removed from Configtool and config/printer*. Simple goal: less distraction for inexperienced users.

All these debug texts are certainly helpful and I use them a lot, but so far I never used them with this general DEBUG flag. Whenever there's something to find out I switch them on individually in the code. And there's debug.h, of course, convenient for coders which like it a bit more centralized.

**Comment by jbernardis** [comment]
This issue is addressed in branch configtoolPhaseA
