### ISSUE TITLE
"Analog Reference" should be removed from Configtool and config/printer*

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#138]
"Analog Reference" should be removed from Configtool and config/printer*. Goal is less distraction for the inexperienced user.

So far I'm not aware of any controller which uses something else than REFERENCE_AVCC, so it should be safe to limit this flag to the source code using it.

**Comment by jbernardis** [comment]
This issue is addressed in branch configtoolPhaseA

**Comment by Traumflug** [comment]
Picked to experimental. Thank you for the work.

PhaseA branch is now empty and was removed.
