### ISSUE TITLE
Configtool: some mild formatting of the help texts collected from header files

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#148]
At least a strip() and removing not all, but most newlines. Tooltips don't size after line length, but have their own idea on how wide to make the box.

**Comment by Traumflug** [comment]
Thanks to the nice design of Configtool, doing this was no rocket science. Code is on the new issue148 branch, please review.

**Comment by jbernardis** [comment]
I did a quick look at this commit.  Looks like it was more work in the header files than in the actual configtool code. 

I think this looks fine.

**Comment by Traumflug** [comment]
> Looks like it was more work in the header files than in the actual configtool code.

Yep, even a bit more with radio button tooltips now working. :-)

Thanks for the review, picked to experimental and removed the issue148 branch.
