### ISSUE TITLE
TEMP_TABLE values in the board file are no longer aligned

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#154]
This got lost along the way. Hint comment for 7-value ones missing.

**Comment by jbernardis** [comment]
What do you mean - just table alignment?

**Comment by jbernardis** [comment]
I figured out what you were saying and have pushed up a fix for this - also on the presetreset branch, but as a separate commit.   Alignment is difficult if different tables use different algorithms, but I spaced things out and added aligned headings.  I think it's a lot better.  Take a look and let me know what you think.

**Comment by Traumflug** [comment]
Yes, that's what I meant. Picked to experimental, just made it a bit more compact and also updated all the board files.

Thank you very much!
