### ISSUE TITLE
Reset/restore presets in thermistor dialog

### ISSUE THREAD

**Issue by Traumflug** [Traumflug/Teacup_Firmware#155]
Thermistors: using a preset, then changing values should reset the preset-menu to <none>. Also, when modifying, the dialog should compare the given values to the presets and set the preset in the choice if one matches.

**Comment by jbernardis** [comment]
I just pushed up branch presetreset which should take care of this issue.  While implementing it I discovered and fixed a bug in the same file when handling the Steinhart-Hart algorithm (when choosing an SH preset, preset value 6 was assigned to both parameter 6 and parameter 7.)

**Comment by Traumflug** [comment]
Works beautifully :-)

Picked to experimental. Thank you very much.
