### ISSUE TITLE
Add SD_CARD_SELECT_PIN support into configtool

### ISSUE THREAD

**Issue by RaD** [Traumflug/Teacup_Firmware#166]
Self described

**Comment by Traumflug** [comment]
D'oh. You also opened an issue for it. Sorry, missed this. Will take the stuff here.

**Comment by Traumflug** [comment]
Sorry for not adding you earlier as collaborator, @RaD. Just catched up on this, you have write access now. The rules here are simple: create as many branches as you feel need for, but change other branches only in agreement with those who created these branches. Usually I review contributions by cherry-picking from such topic branches over to experimental.

Your patch works indeed fine, I just shortened the label a bit to make it fit into the space available. Then put it to *experimental*.

**Comment by Traumflug** [comment]
Now to the missing bits :-)

- All the distributed board config files need such a line, else it won't work as expected.

        #define SD_CARD_SELECT_PIN <pin>

- All these #defines need a describing comment. These comments may help users compiling from the command line and are also used to create a helping tooltip on the GUI. Yes, we're aware this is duplicate work.

- See issue #169.

**Comment by Traumflug** [comment]
> Usually I review contributions by cherry-picking from such topic branches over to experimental.

This also means, there are no merges. May be unusual, but works very well: #81

**Comment by Traumflug** [comment]
I've just added a commit to *experimental* which distributes SD_CARD_SELECT_PIN to all the board files, along with a describing comment. This should complete this issue. Anything forgotten?

**Comment by RaD** [comment]
OK. I am in Crimea at this time. Will check the change when come back to home and report about.

**Comment by RaD** [comment]
Is this issue actual yet?

**Comment by Traumflug** [comment]
If it works for you we can close it.
