### ISSUE TITLE
RepRap Discount Smart Controller Bqranch

### ISSUE THREAD

**Issue by youssefaly97** [Traumflug/Teacup_Firmware#183]
Hello. So I opened this branch some time ago, I have completed over the LCD3 branch's code to get to:

What's done:

-made a customizable splash screen at start up

-made main menu screen with sub menus (up to 3 levels)

-used the beeper to indicate successful selections and when printer is ready after startup (can be turned off in config.wrapper)

-added debounce code for encoder press down click

-added cursor for selection

What's yet to be done:

-vertical LCD shifting code still needs some work

-might add debouncing code for the encoder wheel itself (it works with about 90% reliability)

-add code for the "back" entry (go up a level in the menu)

-store strings in PROGMEM to go with the Teacup objectives (optimal ram usage)

-connect the actual functions to the menu structures

Please give it a try and tell me about your findings if I missed any while I was testing.

**Comment by Traumflug** [comment]
I think this was meant to go to issue #163.
