### ISSUE TITLE
LCD5-jgrjgr

### ISSUE THREAD

**Issue by jgrjgr** [Traumflug/Teacup_Firmware#184]
Hi all,

i have created another branch which contains my semi working version containing the start of a basic lcd menu and file listing on the lcd, currently it's being developed on the rumba board with a reprepdiscount smart lcd controller.

i used bits and pieces from the other branches so far it is functional to the point:

- the rotary encoder works (2 clicks for every movement)
- the button click works
- there is a series of placeholder menu options( i am putting code behind these to make the properly functional atm)
- files will display on the bottom line of the 4 line lcd one at a time, this is perfectly fine and usable however it's probably desirable to utlise all 3 - 4 lines at some point
- lcd inits and sdcard inits have been swapped around so sdcard mounting information can me displayed on the lcd
- it will attempt once (will increase this) upon powerup to init the sdcard (it only works sporadically at the moment)(i'm going to tie this in with the sdcard detect pin and have it put the letters "SD" on the top right part of the screen when it detects and successfully mounts the sdcard)

in summary we are not far off being able to totally run teacup in a standalone way.

**Comment by Traumflug** [comment]
Also moved to #163.
