### ISSUE TITLE
Professional PID tuning

### ISSUE THREAD

**Issue by youssefaly97** [Traumflug/Teacup_Firmware#188]
I've reached out for help from electrical control engineers to tune the PID loop. They asked about what seems to be known as "The Transfer Function". Can someone give me the transfer function we're using for teacup ?

**Comment by Traumflug** [comment]
The right question would be: "what transfer function has your heater?". It's a property of the heater, not of the controller.

A first step to improve tuning would be to find a procedure to measure this function experimentally. Another approach would be to find a procedure on how to improve the PID values by iteration (try, look at the response, readjust values, repeat, repeat, repeat, ...). A Python script doing this would be awesome, it could be part of Configtool.

**Comment by Traumflug** [comment]
Looks like @Wurstnase takes care of this, let's continue with issue #206.
