### ISSUE TITLE
Z late enable

### ISSUE THREAD

**Issue by Wurstnase** [Traumflug/Teacup_Firmware#202]
In normal mode the z-axis is enabled and disabled after each move.
My z-axis spindle has no self locking and will lose its position.

https://github.com/Traumflug/Teacup_Firmware/commit/f1539f292f

**Comment by Traumflug** [comment]
I'm pretty sure we had this issue a number of times already, so sorry it isn't fixed already :-) And yes, code introducing a config flag would be welcome. Ideally together with a corresponding patch for Configtool.

**Comment by Wurstnase** [comment]
> Ideally together with a corresponding patch for Configtool.

done

**Comment by Traumflug** [comment]
Excellent! Thank you for the contribution. Picked this to *experimental* and removed the topic branch.

I hope you don't mind me renaming Z_LATE_ENABLE to Z_AUTODISABLE. I hope users understand this better.

**Comment by Wurstnase** [comment]
You're welcome. 
Yes, Z_AUTODISABLE is maybe a better naming.
