### ISSUE TITLE
Searching for last G1 Fxxx

### ISSUE THREAD

**Issue by Wurstnase** [Traumflug/Teacup_Firmware#221]
I'm searching where the last feedrate is saved for the next move and can't find it. Any hints are welcome.

For example:

```
G1 F200
G1 X20 ;where is the feedrate saved?
```

**Comment by triffid** [comment]
https://github.com/Traumflug/Teacup_Firmware/blob/experimental/dda.h#L42 I
believe, it simply never clears the value from one move to the next

**Comment by Wurstnase** [comment]
Yes, this could be. Also when I see this lines. https://github.com/Traumflug/Teacup_Firmware/blob/experimental/gcode_process.c#L111-L114

**Comment by Wurstnase** [comment]
Excellent. With that information I introduced M221 into Teacup.
