### ISSUE TITLE
Consistent spacing

### ISSUE THREAD

**Issue by dcousens** [Traumflug/Teacup_Firmware#225]
As someone that uses GitHub quite often for review,  [this](https://github.com/Traumflug/Teacup_Firmware/blob/master/dda.c#L306-L342) spacing is a nightmare, haha.

Thankfully, the inconsistency seems mostly isolated to the `dda_*` files.
@Traumflug did you have a preference?

**edit**: and `temp.c`, and `sendf.c`, and `pinio.c` and `msg.c`

**edit2:** [this](https://github.com/Traumflug/Teacup_Firmware/blob/master/sendf.c#L72) is great

**Comment by dcousens** [comment]
Closing as a duplicate of https://github.com/Traumflug/Teacup_Firmware/issues/204

**Comment by Traumflug** [comment]
Set tab width to 2 and it should look fine.
