### ISSUE TITLE
Hello Friend. Help for teacup+Schild CNC V3

### ISSUE THREAD

**Issue by Ve-nik** [Traumflug/Teacup_Firmware#256]
The situation is this: there Schild CNC V3, there are two backup Spend A4 and A5, I want to tie them thermistor table and a heater in the MOSFET, but as I can not find where to do this firmware. In config.h I have added:
/ ** \ Def TEMP_SENSOR_PIN
Temperature sensor pins a user should be able to choose from in configtool.
All commented out.
* /
// # Define TEMP_SENSOR_PIN AIO1
// # Define TEMP_SENSOR_PIN AIO2
// # Define TEMP_SENSOR_PIN AIO3
// # Define TEMP_SENSOR_PIN AIO4
// # Define TEMP_SENSOR_PIN AIO5
and has added:
/ ** \ Def HEATER_PIN
Heater pins a user should be able to choose from in configtool. All
commented out.
* /
// # Define HEATER_PIN AIO2
// # Define HEATER_PIN AIO4
// # Define HEATER_PIN AIO5
Launch ConfigTool, they appeared, but did not work. I climb through the Arduino section gcode_process.s and see there:

sase 140:
//? --- M140: Set heated bed temperature ---
//? Undocumented.
#ifdef HEATER_BED
if (! next_target.seen_S)
break;
temp_set (HEATER_BED, next_target.S);
#endif
break;
What am I doing wrong, please help. Or I did not go the right way?

**Comment by Wurstnase** [comment]
Can you upload your complete new board.xxx.h file?

**Comment by Ve-nik** [comment]
I apologize if  do something wrong.
[Teacup_Firmware Venik.zip](https://github.com/Traumflug/Teacup_Firmware/files/654498/Teacup_Firmware.Venik.zip)

**Comment by Wurstnase** [comment]
Looks like you are doing it right. The pins you take for the heater don't have PWM but this shouldn't change anything for a test.

So what happened? Or what not?

**Comment by Ve-nik** [comment]
The firmware is compiled, but the program does not work.

**Comment by Wurstnase** [comment]
Does not work can be everything. You should describe exactly what happened. Happened nothing? No serial connection? No feedback at all? Or does the heater do nothing?

Also, maybe a picture of your setup could help. Circuit of your heater-setup and thermistor-setup.

**Comment by Ve-nik** [comment]
Thermistor  hotend work. Thermistor and the hot bed, no. Tried to change only the hot bed for free port AIO0, too, failed. The assembled circuit, a copy of the RAMPS, electronics 100% working.
![default](https://cloud.githubusercontent.com/assets/24586473/21224426/358341a0-c2dd-11e6-8192-37cb1a92ce8e.png)
![default](https://cloud.githubusercontent.com/assets/24586473/21224430/3bd5c672-c2dd-11e6-8430-2d88dd06e369.png)

**Comment by Wurstnase** [comment]
Are you sure, that the pins are connected to the Uno? Can you measure the resistance between the pin on the CNC Shield?

**Comment by Ve-nik** [comment]
My assumption that the problem is with the port assignment on the heated hotbed. UNO and CNC V3 resistance of 0.01 ohms.

**Comment by Ve-nik** [comment]
Maybe can I somehow remap the RX and Tx, but how?

**Comment by Wurstnase** [comment]
> UNO and CNC V3 resistance of 0.01 ohms.

That is ok.
Can you please configure the heated bed to a fan? And check if you can set this fan with M106 S255 on?

> Maybe can I somehow remap the RX and Tx, but how?

No you can't remap the serial connection.

**Comment by Ve-nik** [comment]
Oh yes, it's an idea! Today, I will try. Thank you.

**Comment by Ve-nik** [comment]
Thank you, dear friend. Your advice helped in the decision. The problem was incorrectly marked contacts on the shield (SCL and SDA).I'm in the firmware all pins made fan, and on the next run commands M106 S255  I found the truth.

**Comment by Wurstnase** [comment]
Nice. Which pins are correct now?

**Comment by Ve-nik** [comment]
SLC-AIO5 and SDA-AIO4  inverted.

**Comment by Wurstnase** [comment]
Thanks for the Info. I have also the CNC Shield V3. But currently I don't use the SCL and SDA pins.

If you want 'more' powerfull controller, you could replace the Arduino Uno with a Nucleo F411RE. I'm working on a port since one year.

**Comment by Ve-nik** [comment]
NUCLEO-F411RE excellent platform 32bit perhaps necessary preobresti and study quietly. 8-16 bits already obsolete.

**Comment by Wurstnase** [comment]
I close this, because it's solved.
