### ISSUE TITLE
Print result not smooth (delta printer)

### ISSUE THREAD

**Issue by ryannining** [Traumflug/Teacup_Firmware#273]
![image](https://user-images.githubusercontent.com/11457832/26982707-6ba863ee-4d63-11e7-8c1a-fe1533e2f618.png)

![image](https://user-images.githubusercontent.com/11457832/26982847-f2715e30-4d63-11e7-9fc5-e0eb4d9e0788.png)

After succesfully print using DELTA printer on Nano 328P, there still some problem. Looks like the motion is not smooth betwen gcode line segment. I dont know if this because gcode parsing not fast enough or, each line segment startup calculation is not fast enough.

But judging from other firmware such repetier can do this smoothly, there must be something we can do.

Tomorow will test on cartesian printer, check if this is just DELTA problem or not.

**Comment by ryannining** [comment]
After check, looks not gcode parser problem, and queue is full.

Then after change acceleration from 300 to 8000, its become lot smoother.

Does this mean the acceleration lookahead doesnot  remove ramps up/down on crossing ?

Now printing the dragon again using accel=8000 .

**Comment by Traumflug** [comment]
> Does this mean the acceleration lookahead doesnot remove ramps up/down on crossing ?

Depends on your lookahead settings.

**Comment by ryannining** [comment]
Look ahead is turned on, thats only the setting we have right ? oh the jerk, i use 20.

**Comment by ryannining** [comment]
Result accel = 300 vs 8000

![image](https://user-images.githubusercontent.com/11457832/26998174-dc24e204-4daa-11e7-9ecb-e909da61c42f.png)
![image](https://user-images.githubusercontent.com/11457832/26998180-e92f812a-4daa-11e7-8ccb-e4d58854a9d3.png)

Its better....

**Comment by Wurstnase** [comment]
The yerk-setting in Teacup is mm/min. 20 is very low. In the simulator you will see no big diffences with low yerk or lookahead off. 

I would test this with ~1000 acceleration and ~1200 yerk.

**Comment by ryannining** [comment]
Thx, yes its work, should i close this issue. So next, I am working on compatibility with Repetier Host (including the EEPROM manager).
