### ISSUE TITLE
Broken Serial Communication

### ISSUE THREAD

**Issue by YaseenTwati** [Traumflug/Teacup_Firmware#280]
I Built my own custom Controller PCB around the **ATMEGA328P** running at 20Mhz
i can successfully build the firmware and upload it, but serial communication doesn't seem to work work
i basically receive garbage on the computer side ( same sort  of garbage you'd get from a wrong baud rate )
i tried multiple baud rates, no success, 
tried running my board on its internal 8Mhz, same problem
tried using a simple arduino sketch to print "Hi" just to make sure that serial works .. and it does
tried different adapters just in case ( serial to usb and the uart bluetooth module )
i couldn't get this to work
lastly but not least 
i tried  uploading the firmware to a bare arduino uno which isnt connected to anything just to check the serial response .. same exact problem.
am i missing something ?

**Comment by YaseenTwati** [comment]
tried all lol
Arduino IDE
config tool
Makefile

**Comment by Wurstnase** [comment]
Just doing some tests some days ago with the master and experimental on an atmega2560 at 16MHz. No issue at all. 

Someone on an old Gen7 1.5 with 20MHz had also no problems.

**Comment by YaseenTwati** [comment]
@Wurstnase 
Weird, its probably something with my setup on the software/buid side since the hardware seems to be okay
just couldn't get what it is ...
if you have time, is there anything weird about my board config and Makefile ? 

[Makefile.txt](https://github.com/Traumflug/Teacup_Firmware/files/1431789/Makefile.txt)

[board.spiro.h.txt](https://github.com/Traumflug/Teacup_Firmware/files/1431792/board.spiro.h.txt)

**Comment by YaseenTwati** [comment]
ill edit the code to generate a square wave signal and check it with my oscilloscope
to check if the code is running at the correct frequency ..

**Comment by Wurstnase** [comment]
I can't find any special. 
Only your baudrate looks like pretty slow. But that shouldn't be the problem. 

How does your Arduino test sketch looks like?
How is the schematic of your board?

**Comment by YaseenTwati** [comment]
After messing around and doing some Oscilloscope tests
the first test failed which means code was running at wrong frequency 
i went through changing the fuses again and it worked this time .. even though i changed the many times earlier ...

![wrongfreq](https://user-images.githubusercontent.com/7010334/32246603-2cad7f80-be88-11e7-97b4-9e7d22ba12c4.png)

![8mhz_normal](https://user-images.githubusercontent.com/7010334/32246568-085a9654-be88-11e7-867e-9870d7ffb312.png)
![teacupspeed_correct](https://user-images.githubusercontent.com/7010334/32246585-18875742-be88-11e7-8390-a12128c6622e.png)

conclusion : problem with my fuses and not teacup
sorry for the trouble, 
Thanks for the help
