### ISSUE TITLE
configtool.py not opening

### ISSUE THREAD

**Issue by CNCLover** [Traumflug/Teacup_Firmware#291]
Hi,

I have tried to open configtool.py with various versions of python (3.6.4, 2.7.14,...) but failed.

Python window opens for very short time and automatically closes.

I have 64 bit windows laptop.

Thanks

**Comment by Wurstnase** [comment]
Please check issue #281.

**Comment by CNCLover** [comment]
I sloved by installin wxpython. Thanks
