### ISSUE TITLE
Different steps per meter for x and y axis

### ISSUE THREAD

**Issue by CNCLover** [Traumflug/Teacup_Firmware#293]
Hi,

When build with different rated stepper motor for x and y axis, ie. different steps per meter for x and y axis, it shows error. 

Please help me to come  out this problem.

I also don't want to use hot bed and thermistor. Which changes are required?

Thanks

**Comment by Gabriela78** [comment]
@CNCLover 
in Printer>Acceleration tab uncheck Look Ahead 
 "Look-ahead requires steps per m to be identical on the X and Y axis (for now)"
In Printer tab Heaters delete unused Heater Fan etc Temperature sensor do the same .
 br.
for cnc try to use this branch https://github.com/Traumflug/Teacup_Firmware/tree/arc-support
http://reprap.org/wiki/Teacup_Firmware

**Comment by CNCLover** [comment]
Thanks
