### ISSUE TITLE
Tool pids affected by bed pids

### ISSUE THREAD

**Issue by phord** [Traumflug/Teacup_Firmware#301]
I noticed if the bed heater is maintaining a setpoint then the tool heater drifts by +/- 5 degrees.  But if the bed heater is solid-on or solid-off, the tool temperature only drifts half a degree.  Why are the correlated?  Is it real or is it a read inaccuracy?

![screenshot from 2018-07-07 21-10-01](https://user-images.githubusercontent.com/123908/42416688-dec93234-822a-11e8-9720-ce05bd32e07b.png)

**Comment by triffid** [comment]
power supply noise, or poor load regulation?

**Comment by Wurstnase** [comment]
I had some years a similar issue. In my case was it a bad layout from the shield. A switching regulator was close to the ADC line.

**Comment by phord** [comment]
Could be.  Cheap-o RAMPS 1.4.  I guess I know even better why we have TEMP_EWMA now.  :imp:

**Comment by phord** [comment]
Hm.  Obviously I should move my Gen7 board over since I no longer use the printer it is attached to.  And because this RAMPS 1.4 [may be a fire hazard](https://reprap.org/wiki/RAMPS_1.4#WARNING_-_THERMAL-isolation-related_DESIGN_FLAW_IN_Power_handling_capacity_of_PRODUCTION_RAMPS_1.4_boards).
