### ISSUE TITLE
Acceleration > 100 causes sporadic speeds

### ISSUE THREAD

**Issue by phord** [Traumflug/Teacup_Firmware#69]
When ACCELERATION is 10, we seem able to accelerate up to our target speed without fail.  When ACCELERATION is 100 or more, our maximum speed is much lower than the target speed and is spiky.

Here's a graph of our measured velocity for this script at several different ACCELERATION values:

```
G1 X30 F300
G1 X60 F300
G1 X90 F300
G1 X120 F300
G1 X150 F300
G1 X180 F300
M2
```

![image](https://f.cloud.github.com/assets/123908/1659391/fec91e54-5ba2-11e3-8082-e9e7d34e32cd.png)

When lookahead is turned on, it seems to work ok for moves after the 2nd one.  But the target speed is still unreached and the moves are still spiky.

![image](https://f.cloud.github.com/assets/123908/1659408/4e4045ac-5ba3-11e3-9b69-e94844fa3313.png)

**Comment by Wurstnase** [comment]
When dda->n is > 65535, int_inv_sqrt() will overflow. This will only occurs at very high step rates with relative slow accelerations. AVRs are too slow for this.

Maybe the LPC can reach this?
The STM32 with TMC2130 at 1/256 µ-steps will reach this easily.

```
a = v^2 / (2*s)

with s = _S_ * sm where _S_ = steps and sm = steps/mm

sm = a * 2 * _S_ / v^2

v_max = max_frequency / sm

sm = max_frequency^2 / (a * 2 * _S_)

overflow when _S_ > 65535

=> sm * a = max_frequency^2 / (2 * 65535)
```

**Comment by Traumflug** [comment]
Another reason to switch to calculating speed first, then the required step delay from that, isn't it? This way there is no square and no root involved, overflows can't happen.

That said, the original issue here is an entirely different one. Teacup misses one step delay calculation after finishing the acceleration ramp, so actual top speed can be up to 33% smaller than the wanted target speed if there are only 2 acceleration steps.

**Comment by Wurstnase** [comment]
> Teacup misses one step delay calculation after finishing the acceleration ramp, so actual top speed can be up to 33% smaller than the wanted target speed if there are only 2 acceleration steps.

Ok. So this issue is finally solved?!?

> Another reason to switch to calculating speed first

Yes. I have currently too much projects. New printer, lots of new code... More soon(tm)

**Comment by Traumflug** [comment]
> So this issue is finally solved?!?

Not to my knowledge.

> I have currently too much projects.

Me, too. :-)

**Comment by Wurstnase** [comment]
>> So this issue is finally solved?!?

> Not to my knowledge.

I not really sure about this issue. The speed will vary in the end and doesn't reach the expected speed?
On my tests the speed also vary. There it comes from the dda_clock. It accelerate for a specific distance. rampup_steps. But dda_clock changes only every 2ms. So when you accelerate and you are beyond rampup_steps the current code won't change the speed anymore.

**Comment by Traumflug** [comment]
It's here: https://github.com/Traumflug/Teacup_Firmware/blob/master/dda.c#L871

Speed (`recalc_speed`) is (re-)calculated and applied only during acceleration and deceleration ramps. During the constant speed part it isn't, so speed sticks at the last acceleration step. Barely noticeable if there are 1000 or more such acceleration steps; deviation is less than 0.1%, then. Very noticeable if there are only 3 acceleration steps; deviation up to 33%.

**Comment by Wurstnase** [comment]
Yes, that's exactly what I've mean.
In Marlin they calculate in advance the 'travelspeed' and apply it.

So we have 3 states in this case.
- recalc when accelerating
- recalc when decelerating
- apply top speed

**Comment by Wurstnase** [comment]
This should fix it:
https://github.com/Traumflug/Teacup_Firmware/tree/issue-69a

**Comment by phord** [comment]
Nice!  This fix at issue-69a does appear to fix this issue in the simulator.  I haven't tried it on my printer, though.  Notice the top of all the speeds in this graph is the same.

![screenshot from 2016-11-14 14-01-41](https://cloud.githubusercontent.com/assets/123908/20284695/0d7cc0f0-aa73-11e6-964c-765198f7fcf6.png)

**Comment by Wurstnase** [comment]
Yes, I run my last dry print also with this code.
Also you can hear it. Just test it with running the motor at the same range with the same speed. The sound at top speed is not different anymore.

**Comment by Wurstnase** [comment]
Maybe the comparison of `dda->c > dda->c_min` needs to be atomic. I'm not sure.

**Comment by Traumflug** [comment]
Code needs to be atomic if the variables used can be changed by an interrupt. Related interrupt code is in dda_step() and dda_start().

**Comment by Wurstnase** [comment]
Ok, when a new dda comes alive, the dda->c_min could change and we will get a jump in speed. So we should also check the ID like the lines before.

**Comment by Wurstnase** [comment]
Last two commits of https://github.com/Traumflug/Teacup_Firmware/commits/issue-69a could be squashed.

**Comment by phord** [comment]
Just a note for future-me:

I read this code several times without understanding why it's not backwards.

       if (dda->c > dda->c_min) {
         dda->c = dda->c_min;
       }

This happens only when !recalc_speed, meaning we are cruising, not accelerating or decelerating.  So it pegs our dda->c at c_min if it never made it as far as c_min.  Maybe the comments can be clearer or the conditions made more obvious.

**Comment by Wurstnase** [comment]
I made an update of that old issue-69 branch. So we could use this also later for testing.
https://github.com/Traumflug/Teacup_Firmware/tree/issue-69c
