### ISSUE TITLE
How to configure installation for Arduino UNO R3?

### ISSUE THREAD

**Issue by techboycr** [Traumflug/Teacup_Firmware#86]
Hi! this is a great project tahnk you so much for this contribution, I am trying to make a small 3d printer using Stepper servos from Old Cd Roms and Easy Stepper Driver from Sparkfun all this connected to an Arduino Uno.

My questions are:

1. Do Easy Stepper Driver work with this firmware? https://www.sparkfun.com/products/10267

2. How do I configure Teacup for Arduino UNO R3?

Thanks in advance for your help.

**Comment by Traumflug** [comment]
> >    I got the config.h file for Arduino UNO would you like to put it in the firmware download?

> Thanks for the offering, but it won't help others much, because pin mapping depends on how each user wires his electronics.

With Configtool coming along, it looks like I should change my mind here. Wiring is still unpredictable, but the board file in config/ now also defines which CPUs are available, their frequency and such stuff.

Still here, @techboycr? Board files are a subset of the former config.h files. Still well documented, should be easy to edit.

**Comment by techboycr** [comment]
Still here! Ok I will look for it and put it on a different Branch maybe.

**Comment by parapapapaal** [comment]
Hello. I'm building a 3D printer and CNC. I am working with Arduino Uno and had compatibility issues with the firmware. I discovered that with Teacup could solve the problem of pins, but when I do "Build" I get an error. Then, in the Arduino IDE does not let me up, did not find the board.arduinouno (my configuration) directory. We are Spanish and don't understand very well teacup in English, then I do not know if I'm writting wrong setting. Could you upload the file config Arduino one? I know that the pins do not serve me but I can change. Thank you!

**Comment by Traumflug** [comment]
> when I do "Build" I get an error

Which error?

> We are Spanish and don't understand very well teacup in English

But you certainly know the concept of "Copy & Paste". Please copy the error message here.

> Could you upload the file config Arduino one?

No. Because there's no crystal ball which magially detects how you wired your controller.

**Comment by parapapapaal** [comment]
El error que me da es "type error: coercing to unicode: need string or buffer, tuple found."

Y ya sé que no me va a detectar mis pines mágicamente, pero no estoy utilizando una Ramps, estoy utilizando un circuito impreso que he hecho yo mismo y por lo tanto puedo cambiar físicamente los pines a mi antojo, es decir, puedo conectar los drivers al pin que yo quiera. Por ello pedía la configuración, porque, aunque los pines sepa conectarlos, hay otros datos que no sé que significan. Gracias.

**Comment by Traumflug** [comment]
> "type error: coercing to unicode: need string or buffer, tuple found."

Thanks.

Google translation of the remaining part:

> And I know that I will not detect my pin magically, but I'm not using Ramps, I am using a printed circuit've done it myself and therefore I can physically change the pin at will, ie I can connect drivers I want to pin. She therefore requested the setting, because, although the pins connect know, there are other data that does not mean I know.

I'd start with the cnc-shield-v3 or nanohearth board (*Menu -> File -> Load board*). Both are made for Arduino Nano based controllers, which feature the same ATmega as an Arduino Uno.

----
@jbernardis, do you have an idea where Configtool could find a tuple instead of a string? I take this runs on a spanish installation, so something being one word in english might be two words there.

**Comment by parapapapaal** [comment]
El error que te comento me aparece con la configuración que me has dicho ("cnc-shield-v3"), que es la que utilizo porque es la más parecida a Arduino Uno.

**Comment by Traumflug** [comment]
> The error that you commented appears with the settings I've said ("cnc-shield-v3"), which is what I use because it is the most similar to Arduino Uno.

So we found a bug. Nice :-)

Good news is, I get a similar error here when loading this board config and selecting Build:

```
Traceback (most recent call last):
  File "./configtool.py", line 428, in onBuild
    self.onBuildorUpload(True)
  File "./configtool.py", line 509, in onBuildorUpload
    dlg = Build(self, self.settings, f_cpu, cpu)
  File "/home/mah/RepRap/Teacup_Firmware/configtool/build.py", line 192, in __init__
    self.compile()
  File "/home/mah/RepRap/Teacup_Firmware/configtool/build.py", line 195, in compile
    self.generateCompileScript()
  File "/home/mah/RepRap/Teacup_Firmware/configtool/build.py", line 244, in generateCompileScript
    opts = opts.replace("%F_CPU%", self.f_cpu)
TypeError: expected a character buffer object
```

I'll work on a fix.

**Comment by parapapapaal** [comment]
Muchas gracias. Sería un favor enorme.

**Comment by Traumflug** [comment]
Fix is on branch *experimental*, the commit just above this post. Thanks for reporting and please let us know wether it works.

BTW., building for any board was broken :-}

**Comment by Traumflug** [comment]
Zero feedback.

Lets close this before I get angry.

**Comment by dbotdyu** [comment]
the arduino directory is where i have kept my arduino IDE right?

**Comment by dbotdyu** [comment]
If I understood right from this conversation, Teacup can work with Repetier?
